version: "3.7"

services:
  # app:
  #   container_name: app
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./:/app
  #   networks:
  #     - backend
  #   links:
  #     - api_database
  #     - crm_database
  #   depends_on:
  #     - api_database
  #     - crm_database

  db:
    container_name: db
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
